version: "2"
services:
   namenode:
      image: elek/hadoop-hdfs-namenode
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   datanode:
      image: elek/hadoop-hdfs-datanode
      volumes:
         - "{{env.DATA_DIR}}:/data"
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   resourcemanager:
      image: elek/hadoop-yarn-resourcemanager
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   nodemanager:
      image: elek/hadoop-yarn-nodemanager
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   zeppelin:
      image: elek/zeppelin
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zeppelin"
   zookeeper:
      image: elek/zookeeper
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zookeeper"
   hbasemaster:
      image: elek/hbase-master
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hbase"
   hbaseregion:
      image: elek/hbase-regionserver
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hbase"
   sparkmaster:
      image: elek/spark-master
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "spark"
   sparkhistory:
      image: elek/spark-history
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "spark"
