version: "2"
services:
   namenode:
      container_name: namenode
      image: elek/hadoop-hdfs-namenode
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   datanode:
      container_name: datanode
      image: elek/hadoop-hdfs-datanode
      volumes:
         - "{{env.DATA_DIR}}:/data"
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   resourcemanager:
      container_name: resourcemanager
      image: elek/hadoop-yarn-resourcemanager
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   nodemanager:
      container_name: nodemanager
      image: elek/hadoop-yarn-nodemanager
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   zeppelin:
      container_name: zeppelin
      image: elek/zeppelin
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zeppelin"
   zookeeper:
      container_name: zookeeper
      image: elek/zookeeper
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zookeeper"
   hbasemaster:
      container_name: hbasemaster
      image: elek/hbase-master
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hbase"
   hbaseregion:
      container_name: hbaseregion
      image: elek/hbase-regionserver
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hbase"
   sparkmaster:
      container_name: sparkmaster
      image: elek/spark-master
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "spark"
   sparkhistory:
      container_name: sparkhistory
      image: elek/spark-history
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "spark"
         A: "xxx"
