version: "2"
services:
   datanode:
      image: elek/hadoop-hdfs-datanode
      volumes:
         - "{{env.DATA_DIR}}:/data"
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   nodemanager:
      image: elek/hadoop-yarn-nodemanager
      network_mode: host
      volumes:
         - "{{env.DATA_DIR}}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   hbaseregion:
     image: elek/hbase-regionserver
     network_mode: host
     volumes:
        - "{{env.DATA_DIR}}:/data"
     environment:
        CONFIG_TYPE: "consul"
        CONFIG_KEY: "hbase"
