version: "2"
services:
   consul:
      image: progrium/consul
      network_mode: host
      command: "--server -join 192.168.50.4"
   consulcompose:
      image: elek/consul-compose
      network_mode: host
      volumes:
         - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
         CONSUL_COMPOSE_PATH: "conf/compose/node3.yaml"
         CONSUL_SERVER: "localhost:8500"
