version: "2"
services:
{% include 'compose/slave.yaml' %}
  #  flume:
  #     container_name: flume
  #     image: elek/flume
  #     network_mode: host
  #     volumes:
  #        - "${DATA_DIR}:/data"
  #     environment:
  #        CONFIG_TYPE: "consul"
  #        CONSUL_KEY: "flume"
   stormui:
      container_name: stormui
      image: elek/storm-ui:1.0.3
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "storm"
