version: "2"
services:
   namenode:
      container_name: namenode
      image: elek/hadoop-hdfs-namenode:2.8.0
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   resourcemanager:
      container_name: resourcemanager
      image: elek/hadoop-yarn-resourcemanager:2.8.0
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   # hbasemaster:
   #    container_name: hbasemaster
   #    image: elek/hbase-master
   #    volumes:
   #     - "${DATA_DIR}:/data"
   #    network_mode: host
   #    environment:
   #       CONFIG_TYPE: "consul"
   #       CONSUL_KEY: "hbase"
   zookeeper:
      container_name: zookeeper
      image: elek/zookeeper
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zookeeper"
   zeppelin:
      container_name: zeppelin
      image: elek/zeppelin:0.7.0
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zeppelin"
   sparkhistory:
      container_name: sparkhistory
      image: elek/spark-history:2.1.0
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "spark"
   stormnimbus:
      container_name: nimbus
      image: elek/storm-nimbus
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "storm"
   datanode:
      container_name: datanode
      image: elek/hadoop-hdfs-datanode:2.8.0
      volumes:
         - "${DATA_DIR}:/data"
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
