version: "2"
services:
{% include 'compose/slave.yaml' %}
   namenode:
      container_name: namenode
      image: elek/hadoop-hdfs-namenode:latest
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   resourcemanager:
      container_name: resourcemanager
      image: elek/hadoop-yarn-resourcemanager:latest
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   hbasemaster:
      container_name: hbasemaster
      image: elek/hbase-master
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hbase"
   zookeeper:
      container_name: zookeeper
      image: elek/zookeeper
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zookeeper"
   zeppelin:
      container_name: zeppelin
      image: elek/zeppelin:0.7.0
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zeppelin"
   postgres:
      container_name: postgres
      image: postgres:9.6.1-alpine
      network_mode: host
