version: "2"
services:
   datanode:
      image: elek/hadoop-hdfs-datanode
      volumes:
         - "/tmp:/data"
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "hdfs"
   nodemanager:
      image: elek/hadoop-yarn-nodemanager
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "yarn"
   hbaseregion:
      image: elek/hbase-regionserver
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONFIG_KEY: "hbase"
   weavescope:
       image: weaveworks/scope:1.1.0
       privileged: true
       network_mode: host
       pid: "host"
       volumes:
           - "/var/run/docker.sock:/var/run/docker.sock"
           - "/var/run/scope/plugins:/var/run/scope/plugins"
       environment:
          CHECKPOINT_DISABLE:
       command: "--probe.docker=true"
