version: "2"
services:
   zeppelin:
      image: elek/zeppelin
      network_mode: host
      environment:
         CONFIG_TYPE: "consul"
         CONSUL_KEY: "zeppelin"
   sparkmaster:
      image: elek/spark-master
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONFIG_KEY: "spark"
   sparkhistory:
      image: elek/spark-history
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONFIG_KEY: "spark"
   livy:
      image: elek/livy
      network_mode: host
      volumes:
         - "${DATA_DIR}:/data"
      environment:
         CONFIG_TYPE: "consul"
         CONFIG_KEY: "spark"
